/** Localized labels stay beside the controls, keeping the preference schema language-independent. */
export const sceneryCopy = {
  zh: {
    preview: '当前页面 · 即时预览',
    looks: '光影预设',
    custom: '自定义',
    image: '图片与光影',
    text: '标题排印',
    advanced: '色彩与取景',
    reset: '重置本页设置',
    resetBanner: '重置横幅',
    resetEffects: '重置氛围',
    imageOpacity: '图片不透明度',
    mask: '遮罩强度',
    maskStyle: '遮罩方式',
    tone: '色调',
    brightness: '亮度',
    contrast: '对比度',
    saturation: '饱和度',
    blur: '柔焦',
    focusX: '水平取景',
    focusY: '垂直取景',
    edge: '底部衔接',
    textOpacity: '文字不透明度',
    textSize: '标题大小',
    textWeight: '字重',
    textSpacing: '字间距',
    textShadow: '文字阴影',
    textColor: '文字颜色',
    textFont: '标题字体',
    density: '数量',
    speed: '速度',
    effectOpacity: '特效不透明度',
    lookNames: ['原片', '晨雾柔光', '暖调胶片', '蓝调时刻', '黑白银盐', '影院暗角'],
    effects: ['关闭', '樱花', '轻雪', '细雨', '萤火', '星光', '落叶', '光斑', '极光'],
    effectHint: '轻柔点缀，不影响点击。关闭页面或切到后台时暂停。',
    reduced: '系统或阅读设置已减少动态效果，当前暂停播放。',
    loadFailed: '特效暂时未能加载。网络恢复后可重新选择，或刷新页面重试。',
    bannerHint: '仅改变显示效果，不修改原图。设置适用于所有页面。',
    choices: {
      maskStyle: ['均匀遮罩', '上下渐变', '边缘暗角'],
      tone: ['自然', '暖调', '冷调'],
      edge: ['波浪', '柔和渐隐', '平直'],
      textColor: ['白色', '墨色', '主题正文色'],
      textFont: ['跟随主题', '圆体', '衬线'],
      textWeight: ['常规', '中等', '半粗', '粗体', '特粗'],
    },
  },
  en: {
    preview: 'This page · live preview',
    looks: 'Light & color',
    custom: 'Custom',
    image: 'Image & light',
    text: 'Title typography',
    advanced: 'Color & framing',
    reset: 'Reset settings',
    resetBanner: 'Reset banner',
    resetEffects: 'Reset effects',
    imageOpacity: 'Image opacity',
    mask: 'Overlay strength',
    maskStyle: 'Overlay',
    tone: 'Color tone',
    brightness: 'Brightness',
    contrast: 'Contrast',
    saturation: 'Saturation',
    blur: 'Soft focus',
    focusX: 'Horizontal focus',
    focusY: 'Vertical focus',
    edge: 'Lower edge',
    textOpacity: 'Text opacity',
    textSize: 'Title size',
    textWeight: 'Weight',
    textSpacing: 'Letter spacing',
    textShadow: 'Text shadow',
    textColor: 'Text color',
    textFont: 'Title font',
    density: 'Amount',
    speed: 'Speed',
    effectOpacity: 'Effect opacity',
    lookNames: ['Original', 'Morning haze', 'Warm film', 'Blue hour', 'Silver print', 'Cinema'],
    effects: ['Off', 'Petals', 'Snow', 'Rain', 'Fireflies', 'Stars', 'Leaves', 'Bokeh', 'Aurora'],
    effectHint: 'A light touch that never intercepts clicks. Pauses in hidden tabs.',
    reduced: 'Paused by your system or reading motion preference.',
    loadFailed: 'The effect could not load. Choose it again when online, or reload to retry.',
    bannerHint: 'Display only; originals stay intact. Applies across all pages.',
    choices: {
      maskStyle: ['Uniform', 'Gradient', 'Vignette'],
      tone: ['Natural', 'Warm', 'Cool'],
      edge: ['Waves', 'Soft fade', 'Straight'],
      textColor: ['White', 'Ink', 'Theme text'],
      textFont: ['Theme', 'Rounded', 'Serif'],
      textWeight: ['Regular', 'Medium', 'Semibold', 'Bold', 'Extra bold'],
    },
  },
  ja: {
    preview: 'このページ · ライブプレビュー',
    looks: '光と色',
    custom: 'カスタム',
    image: '画像と光',
    text: 'タイトル',
    advanced: '色彩と構図',
    reset: '設定を戻す',
    resetBanner: 'バナーをリセット',
    resetEffects: '効果をリセット',
    imageOpacity: '画像の不透明度',
    mask: 'マスクの強さ',
    maskStyle: 'マスク',
    tone: '色調',
    brightness: '明るさ',
    contrast: 'コントラスト',
    saturation: '彩度',
    blur: 'ぼかし',
    focusX: '水平位置',
    focusY: '垂直位置',
    edge: '下端',
    textOpacity: '文字の不透明度',
    textSize: 'タイトルサイズ',
    textWeight: '太さ',
    textSpacing: '字間',
    textShadow: '文字の影',
    textColor: '文字色',
    textFont: '書体',
    density: '量',
    speed: '速度',
    effectOpacity: '効果の不透明度',
    lookNames: ['オリジナル', '朝もや', '暖色フィルム', '青の時間', '銀塩', 'シネマ'],
    effects: ['オフ', '桜', '雪', '雨', '蛍', '星', '落ち葉', '玉ぼけ', 'オーロラ'],
    effectHint: 'クリックを妨げません。非表示のタブでは停止します。',
    reduced: 'システムまたは読書設定により動きを停止しています。',
    loadFailed: '効果を読み込めませんでした。接続後に再選択するか、ページを再読み込みしてください。',
    bannerHint: '原画は変更しません。全ページに適用されます。',
    choices: {
      maskStyle: ['均一', 'グラデーション', '周辺減光'],
      tone: ['自然', '暖色', '寒色'],
      edge: ['波', 'フェード', '直線'],
      textColor: ['白', '墨色', 'テーマ文字色'],
      textFont: ['テーマ', '丸ゴシック', '明朝'],
      textWeight: ['標準', '中', 'やや太い', '太字', '極太'],
    },
  },
};
