/** Localized labels stay beside the controls, keeping the preference schema language-independent. */
export const sceneryCopy = {
  zh: {
    preview: '当前页面 · 即时预览',
    looks: '光影预设',
    custom: '自定义',
    image: '图片与光影',
    text: '标题排印',
    advanced: '色彩与取景',
    reset: '重置本页设置',
    resetBanner: '重置横幅',
    resetEffects: '重置氛围',
    imageOpacity: '图片不透明度',
    mask: '遮罩强度',
    maskStyle: '遮罩方式',
    tone: '色调',
    brightness: '亮度',
    contrast: '对比度',
    saturation: '饱和度',
    blur: '柔焦',
    focusX: '图片左右位置',
    focusY: '图片上下位置',
    framingHint: '横幅会填满显示区域，超出的部分被裁掉。调整位置可保留人物或风景；50% 为居中，不是缩放。',
    noCropX: '当前宽度已完整显示，左右调整不会产生位移。',
    noCropY: '当前高度已完整显示，上下调整不会产生位移。',
    left: '保留左侧',
    right: '保留右侧',
    top: '保留顶部',
    bottom: '保留底部',
    ambientHeading: '画面环境光',
    ambientLight: '环境光范围',
    ambientHint: '将横幅原色投射到整个页面，滚动后依然保留。只调整环境光，不改变图片、主题与文字颜色。',
    lightOpacity: '光晕强度',
    lightBlur: '柔化程度',
    lightSpread: '扩散范围',
    lightBrightness: '投影亮度',
    lightContrast: '投影对比度',
    lightSaturation: '投影饱和度',
    lightThemeBlend: '主题底色混合',
    lightFeather: '边缘羽化',
    lightDirection: '投影方向',
    lightSurface: '页面底衬',
    lightTextShadow: '文字柔光',
    ambientLooks: '快速调色',
    ambientProjection: '投影与边缘',
    ambientSurfaces: '界面融合',
    ambientSoft: '柔和映色',
    ambientImmersive: '沉浸原色',
    ambientVivid: '浓郁光场',
    ambientSurfaceHint: '所有页面的侧栏与正文共用连续的阅读底衬。图片保持清晰，阅读对比不足时可提高底衬；不透明面板设置优先。',
    edge: '底部衔接',
    textOpacity: '文字不透明度',
    textSize: '标题大小',
    textWeight: '字重',
    textSpacing: '字间距',
    textShadow: '文字阴影',
    textColor: '文字颜色',
    textFont: '标题字体',
    density: '数量',
    speed: '速度',
    effectOpacity: '特效不透明度',
    lookNames: ['原片', '晨雾柔光', '暖调胶片', '蓝调时刻', '黑白银盐', '影院暗角'],
    effects: ['关闭', '樱花', '轻雪', '细雨', '萤火', '星光', '落叶', '光斑', '极光'],
    effectHint: '轻柔点缀，不影响点击。关闭页面或切到后台时暂停。',
    reduced: '系统或阅读设置已减少动态效果，当前暂停播放。',
    loadFailed: '特效暂时未能加载。网络恢复后可重新选择，或刷新页面重试。',
    bannerHint: '仅改变显示效果，不修改原图。设置适用于所有页面。',
    choices: {
      maskStyle: ['均匀遮罩', '上下渐变', '边缘暗角', '顶部遮光', '底部遮光', '中央聚光', '薄雾柔光'],
      tone: ['自然', '暖调', '冷调'],
      edge: ['波浪', '柔和渐隐', '平直', '弧形留白', '斜切', '层叠山峦', '雾化消融'],
      ambientLight: ['关闭', '四周光晕', '全页漫射'],
      lightDirection: ['全方向', '两侧', '上方', '下方'],
      textColor: ['白色', '墨色', '主题正文色'],
      textFont: ['跟随主题', '圆体', '衬线'],
      textWeight: ['常规', '中等', '半粗', '粗体', '特粗'],
    },
  },
  en: {
    preview: 'This page · live preview',
    looks: 'Light & color',
    custom: 'Custom',
    image: 'Image & light',
    text: 'Title typography',
    advanced: 'Color & framing',
    reset: 'Reset settings',
    resetBanner: 'Reset banner',
    resetEffects: 'Reset effects',
    imageOpacity: 'Image opacity',
    mask: 'Overlay strength',
    maskStyle: 'Overlay',
    tone: 'Color tone',
    brightness: 'Brightness',
    contrast: 'Contrast',
    saturation: 'Saturation',
    blur: 'Soft focus',
    focusX: 'Image left / right',
    focusY: 'Image top / bottom',
    framingHint:
      'The banner fills its frame and crops the overflow. Move the crop to keep the subject in view. 50% centers it; this is not zoom.',
    noCropX: 'The full width is visible; moving horizontally has no effect.',
    noCropY: 'The full height is visible; moving vertically has no effect.',
    left: 'Keep left',
    right: 'Keep right',
    top: 'Keep top',
    bottom: 'Keep bottom',
    ambientHeading: 'Image ambient light',
    ambientLight: 'Light coverage',
    ambientHint:
      'Project the banner’s colors across the entire page, even while scrolling. Artwork, theme and text colors stay independent.',
    lightOpacity: 'Light intensity',
    lightBlur: 'Softness',
    lightSpread: 'Spread',
    lightBrightness: 'Projection brightness',
    lightContrast: 'Projection contrast',
    lightSaturation: 'Projection saturation',
    lightThemeBlend: 'Theme blend',
    lightFeather: 'Edge feather',
    lightDirection: 'Projection direction',
    lightSurface: 'Page veil',
    lightTextShadow: 'Text halo',
    ambientLooks: 'Quick looks',
    ambientProjection: 'Projection & edges',
    ambientSurfaces: 'Surface integration',
    ambientSoft: 'Soft color',
    ambientImmersive: 'Immersive color',
    ambientVivid: 'Vivid light',
    ambientSurfaceHint:
      'Sidebar and content share one continuous backing on every page. Images stay clear; increase the veil for stronger reading contrast. Solid panels take priority.',
    edge: 'Lower edge',
    textOpacity: 'Text opacity',
    textSize: 'Title size',
    textWeight: 'Weight',
    textSpacing: 'Letter spacing',
    textShadow: 'Text shadow',
    textColor: 'Text color',
    textFont: 'Title font',
    density: 'Amount',
    speed: 'Speed',
    effectOpacity: 'Effect opacity',
    lookNames: ['Original', 'Morning haze', 'Warm film', 'Blue hour', 'Silver print', 'Cinema'],
    effects: ['Off', 'Petals', 'Snow', 'Rain', 'Fireflies', 'Stars', 'Leaves', 'Bokeh', 'Aurora'],
    effectHint: 'A light touch that never intercepts clicks. Pauses in hidden tabs.',
    reduced: 'Paused by your system or reading motion preference.',
    loadFailed: 'The effect could not load. Choose it again when online, or reload to retry.',
    bannerHint: 'Display only; originals stay intact. Applies across all pages.',
    choices: {
      maskStyle: ['Uniform', 'Gradient', 'Vignette', 'Top shade', 'Bottom shade', 'Spotlight', 'Soft mist'],
      tone: ['Natural', 'Warm', 'Cool'],
      edge: ['Waves', 'Soft fade', 'Straight', 'Arc', 'Diagonal', 'Layered hills', 'Dissolving mist'],
      ambientLight: ['Off', 'Edge glow', 'Full-page light'],
      lightDirection: ['All directions', 'Sides', 'Top', 'Bottom'],
      textColor: ['White', 'Ink', 'Theme text'],
      textFont: ['Theme', 'Rounded', 'Serif'],
      textWeight: ['Regular', 'Medium', 'Semibold', 'Bold', 'Extra bold'],
    },
  },
  ja: {
    preview: 'このページ · ライブプレビュー',
    looks: '光と色',
    custom: 'カスタム',
    image: '画像と光',
    text: 'タイトル',
    advanced: '色彩と構図',
    reset: '設定を戻す',
    resetBanner: 'バナーをリセット',
    resetEffects: '効果をリセット',
    imageOpacity: '画像の不透明度',
    mask: 'マスクの強さ',
    maskStyle: 'マスク',
    tone: '色調',
    brightness: '明るさ',
    contrast: 'コントラスト',
    saturation: '彩度',
    blur: 'ぼかし',
    focusX: '水平位置',
    focusY: '垂直位置',
    framingHint:
      '枠を満たすためにはみ出す部分を切り抜きます。位置を調整して被写体を残します。50% は中央で、ズームではありません。',
    noCropX: '横幅全体が表示されているため、水平移動は見た目を変えません。',
    noCropY: '高さ全体が表示されているため、垂直移動は見た目を変えません。',
    left: '左を残す',
    right: '右を残す',
    top: '上を残す',
    bottom: '下を残す',
    ambientHeading: '画像の環境光',
    ambientLight: '光の範囲',
    ambientHint: 'バナーの色をページ全体へ広げ、スクロール中も保持します。画像・テーマ・文字色とは独立した設定です。',
    lightOpacity: '光の強さ',
    lightBlur: '柔らかさ',
    lightSpread: '広がり',
    lightBrightness: '投影の明るさ',
    lightContrast: '投影のコントラスト',
    lightSaturation: '投影の彩度',
    lightThemeBlend: 'テーマ色の混合',
    lightFeather: '境界のぼかし',
    lightDirection: '投影方向',
    lightSurface: 'ページ背景の不透明度',
    lightTextShadow: '文字の光彩',
    ambientLooks: 'プリセット',
    ambientProjection: '投影と境界',
    ambientSurfaces: 'UIとの調和',
    ambientSoft: '柔らかな色',
    ambientImmersive: '没入する原色',
    ambientVivid: '鮮やかな光',
    ambientSurfaceHint:
      '全ページのサイドバーと本文は共通の下地を使います。画像は鮮明なまま、読みにくい場合は下地を濃くできます。不透明設定を優先します。',
    edge: '下端',
    textOpacity: '文字の不透明度',
    textSize: 'タイトルサイズ',
    textWeight: '太さ',
    textSpacing: '字間',
    textShadow: '文字の影',
    textColor: '文字色',
    textFont: '書体',
    density: '量',
    speed: '速度',
    effectOpacity: '効果の不透明度',
    lookNames: ['オリジナル', '朝もや', '暖色フィルム', '青の時間', '銀塩', 'シネマ'],
    effects: ['オフ', '桜', '雪', '雨', '蛍', '星', '落ち葉', '玉ぼけ', 'オーロラ'],
    effectHint: 'クリックを妨げません。非表示のタブでは停止します。',
    reduced: 'システムまたは読書設定により動きを停止しています。',
    loadFailed: '効果を読み込めませんでした。接続後に再選択するか、ページを再読み込みしてください。',
    bannerHint: '原画は変更しません。全ページに適用されます。',
    choices: {
      maskStyle: ['均一', 'グラデーション', '周辺減光', '上部の陰', '下部の陰', 'スポットライト', '薄霧'],
      tone: ['自然', '暖色', '寒色'],
      edge: ['波', 'フェード', '直線', '弧', '斜線', '重なる丘', '霧の境界'],
      ambientLight: ['オフ', '周囲の光', 'ページ全体'],
      lightDirection: ['全方向', '両側', '上方', '下方'],
      textColor: ['白', '墨色', 'テーマ文字色'],
      textFont: ['テーマ', '丸ゴシック', '明朝'],
      textWeight: ['標準', '中', 'やや太い', '太字', '極太'],
    },
  },
};
